### ISSUE TITLE
How to use refreshAfterWrite

### ISSUE THREAD

**Issue by loinguyentri** [stepio/coffee-boots#142]
When i add refreshAfterWrite option. 
i received java.lang.IllegalStateException: refreshAfterWrite requires a LoadingCache
pls how to i use refreshAfterWrite ?

**Comment by stepio** [comment]
Hello @loinguyentri ,

Sorry for the late reply, I'm sure you found the answer already, will reply just for the sake of documentation.

Short answer: it does not work.

Now the long answer. The error message is correct: using `refreshAfterWrite` requires  `LoadingCache`. Refreshing the value means that it needs to be recalculated by the appropriate key.
Regular cache simply stores whatever you put into it:

1. Build (or load from somewhere) a heavy object.
2. Put that object into cache, associate with certain key.
3. Now you can use that key to retrieve the heavy object from cache.

So you can only retrieve something you previously put there.

Loading cache is smarter cache, which knows how to build the object using the key you provide:

1. Request a heavy object by a key.
2. Cache builds (or loads) that specific heavy object.
3. After building (or loading) the object is stored into the cache, associated with the key.
4. The object returned to the original requestor.

Now back to `refreshAfterWrite`: if we want the ability to get a newer object for the key, the cache should know how to build (load) it. That's why `LoadingCache` is required.

Now back to the library: the aim is to provide easy configuration options through properties, so that you don't need to set up your caches programmatically. You cannot achieve this for `Loading Cache` as you need to specify the "factory method" for building (or loading) the object. And trying to achieve this through properties file would be naive.

Feel free to reopen the issue if you think that I missed something, or need additional clarifications, or would like to prove me wrong by implementing such feature yourself. Have a nice day!
